#!/usr/bin/env bash
# a Bash script that will display information about subdomains.

config () {
	echo "$2 $(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')" | awk '{print "The subdomain " $1" is a " $2 " record and points to " $3}'
}

if [ "$#" -eq 1 ]
then
  config "$1" "www"
  config "$1" "lb-01"
  config "$1" "web-01"
  config "$1" "web-02"
elif [ "$#" -eq 2 ]
then
  config "$1" "$2"
fi
