#!/usr/bin/env bash
# The above line specifies that this script should be executed using the Bash shell.

# Check if at least four arguments were passed to the script.
if [ $# -lt 4 ]; then
    # If not, print a usage message that shows the correct syntax for the script.
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    # Exit the script with an error code of 1.
    exit 1
    
fi

# Assign the first argument to the variable file_path.
file_path="$1"
# Assign the second argument to the variable server_ip.
server_ip="$2"
# Assign the third argument to the variable username.
username="$3"
# Assign the fourth argument to the variable ssh_key_path.
ssh_key_path="$4"


scp -o StrictHostKeyChecking=no -i "$ssh_key_path" "$file_path" "$username@$server_ip:~/"
# Use the scp command to transfer the file specified by file_path to the server specified by server_ip,
# using the username specified by username. The file is copied to the user's home directory on the server.
# The -o StrictHostKeyChecking=no option disables strict host key checking, which can be useful when connecting
# to new or unknown hosts. The -i option specifies the path to the SSH private key that scp should use to authenticate
# with the server.
