#!/usr/bin/env bash

# This script installs and configures an nginx web server on an Ubuntu machine.

# Update the package list
apt-get update

# Install nginx web server
apt-get -y install nginx

# Create default index file
echo "Hello World!" | tee /var/www/html/index.html

# Start nginx web server
service nginx start

# Restart nginx
service nginx restart

