#!/usr/bin/env bash
# Configure a new Nginx server so that /redirect_me is redirecting to another page.
# The redirection must be a “301 Moved Permanently”

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
sudo sed -i '/server_name _;/a \	location /redirect_me {\n		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n	}' /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload

