#!/usr/bin/env bash

# Install Nginx web server
sudo apt-get update && sudo apt-get -y install nginx

# Create a default web page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Set up 301 redirection for /redirect_me
sudo sed -i 's/server_name _;/&\n\trewrite /redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;/' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo systemctl restart nginx

