#!/usr/bin/env bash

set -euo pipefail

# Update the package repository to get the latest packages available for installation.
sudo apt-get update

# Install Nginx web server.
sudo apt-get install -y nginx

# Replace the default Nginx configuration with our custom configuration.
sudo sed -i 's|server_name _;|server_name wantonblack.tech;\n\n    location /redirect_me {\n        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n    }\n\n    |g' /etc/nginx/sites-available/default

# Create a custom index page.
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Create a custom 404 page.
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null

# Configure Nginx to use the custom 404 page.
sudo sed -i '/server_name _;/a \
        error_page 404 /custom_404.html;\n\
        location = /custom_404.html {\n\
            internal;\n\
        }' /etc/nginx/sites-available/default

# Restart the Nginx service to apply the changes made to the configuration.
sudo systemctl restart nginx
