#!/usr/bin/env bash
# script i used to install nginx on my local web server
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World" | sudo tee /usr/share/nginx/html/index.html
replacement="location /redirect_me {\nrewrite ^/.*$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n}\n"
sudo sed -i "/# Only for/ i $replacement" /etc/nginx/sites-available/default
sudo touch /usr/share/nginx/html/404.html
sudo chmod 777 /usr/share/nginx/html/404.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
sudo sed -i "s/#error_page 404/error_page 404/" /etc/nginx/sites-enabled/default
sudo service nginx restart

