#!/usr/bin/env bash
# Replace the default Nginx configuration with our custom configuration
sudo sed -i 's|server_name _;|server_name wantonblack.tech;\n\n    error_page 404 /404.html;\n    location = /404.html {\n        internal;\n        root /usr/share/nginx/html;\n        echo "Ceci n'\''est pas une page";\n    }\n\n    # ...|g' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo service nginx restart
~

