#!/usr/bin/env bash

# Install HAProxy
sudo apt-get update
sudo apt-get install haproxy -y

# Get the hostnames of web-01 and web-02 servers
HOSTNAME1=54.144.221.234
HOSTNAME2=100.26.154.245

# Configure HAProxy
sed 's/^[ \t]*//' << EOF | sudo tee -a /etc/haproxy/haproxy.cfg
frontend www-frontend
    bind *:80
    mode http
    default_backend www-backend

backend www-backend
    mode http
    balance roundrobin
    server web-01 $HOSTNAME1:80 check
    server web-02 $HOSTNAME2:80 check
EOF

# Restart HAProxy
sudo haproxy -f /etc/haproxy/haproxy.cfg

