#!/usr/bin/env bash

# Install HAProxy
sudo apt-get update
sudo apt-get install haproxy -y

# Manage haproxy by using init.d
sudo /etc/init.d/haproxy start

# Configure HAProxy
sudo sed -i '$ a\\nbackend lb-01\n\tbalance roundrobin\n\tmode http\n\tserver web-01 52.87.215.121:80 check\n\tserver web-02 54.160.79.52:80 check\n\
frontend http\n\tbind *:80\n\tmode http\n\n\tuse_backend lb-01' /etc/haproxy/haproxy.cfg

# Restart HAProxy
sudo haproxy -f /etc/haproxy/haproxy.cfg

