#!/usr/bin/env bash

# Get current date in the desired format
DATE=$(date +"%d-%m-%Y")

# Generate MySQL dump
mysqldump -u root -p"$1" --all-databases > backup.sql

# Compress dump file to tar.gz archive
tar -czf "$DATE.tar.gz" backup.sql
