#!/usr/bin/env bash
# This script generates a MySQL dump and creates a compressed archive  of it
DATE=$(date +%d-%m-%Y)
mysqldump -u root -p"$1" --all-databases > backup.sql
tar -czf "$DATE.tar.gz" backup.sql
