#!/usr/bin/env bash
# a Bash script with the minimum number of commands to automate your fix.

# remove existing file
sudo rm /etc/nginx/sites-enabled/default

# link the deault file in sites available with sites enabled
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# restart nginx
sudo service nginx restart
