#!/usr/bin/env bash
# A Bash script that displays:
# To infinity and beyond indefinitely
#With a sleep 2 in between each iteration
#I am invincible!!! when receiving a SIGTERM signal
kill -15 "$(pgrep -f 4-to_infinity_and_beyond)"
