#!/usr/bin/env bash
# A Bash script that displays the content of the file /etc/passwd.
FILENAME="/etc/passwd"
while IFS=: read -r username password userid groupid useridinfo homedir command shell
do
	echo "The user $username is part of the $groupid gang, lives in $homedir and rides $command/$shell. $userid's place is protected by the passcode $password, more info about the user here: $useridinfo"
done < $FILENAME
