#!/usr/bin/env bash
# This script parses Apache log files in list format.
# Groups visitors by IP and HTTP status code.
# Displays the number of occurrences, IP, and HTTP status
# code of each log, in sorted order.

awk '{print $1" "$9}' access.log | sort | uniq -c | sort -nr | awk '{print $1" "$2" "$3}'

