#!/usr/bin/env bash
# A Bash script that displays Best School 10 times.
a=1
while [ $a -le 10 ];
do 
	if [ $a -eq 4 ];
	then
		echo "bad luck"
	elif [ $a -eq 8 ];
	then
		echo "good luck"
	else
		echo "Best School"
	fi

	((a++))
done
