#!/usr/bin/env bash
# A Bash script that displays numbers from 1 to 20 and:
# Displays 4 and then bad luck from China for the 4th loop iteration
# Displays 9 and then bad luck from Japan for the 9th loop iteration
# Displays 17 and then bad luck from Italy for the 17th loop iteration
a=1
while [ $a -le 20 ];
do
	case $a in
		4)
			echo "4"
			echo "bad luck from China"
			;;
		9)
			echo "9"
			echo "bad luck from Japan"
			;;
		17)
			echo "17"
			echo "bad luck from Italy"
			;;
		*)
			echo $a
			;;
	esac
	((a++))
done
