#!/usr/bin/env bash
# A Bash script that displays Best School 10 times.
a=1
while [ $a -le 20 ];
do 
	if [ $a -eq 4 ];
	then
		echo $a
		echo "bad luck from China"
	elif [ $a -eq 9 ];
	then
		echo $a
		echo "bad luck from Japan"
	elif [ $a -eq 17 ];
	then
		echo $a
		echo "bad luck from Italy"
	else
		echo $a
	fi

	((a++))
done
