#!/usr/bin/env bash
# Write a Bash script that configures the container to fit the below requirements
# nginx must be running as nginx user
# nginx must be listening on all active IPs on port 8080
# You cannot use apt-get remove
useradd -r -s /bin/false nginx
sed -i 's/listen       80;/listen       8080;/g' /etc/nginx/nginx.conf
chown -R nginx:nginx /var/lib/nginx
chown -R nginx:nginx /var/log/nginx
sudo service nginx restart
