#!/usr/bin/env bash
# Write a Bash script that configures the container to fit the below requirements
# nginx must be running as nginx user
# nginx must be listening on all active IPs on port 8080
# You cannot use apt-get remove
useradd -r -s /bin/false nginx
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i 's/listen       80;/listen       8080;/g' /etc/nginx/nginx.conf
pkill apache2
chmod 644 /etc/nginx/nginx.conf
sudo service nginx restart
