#!/usr/bin/env bash
# Write a Bash script that configures the container to fit the below requirements
# nginx must be running as nginx user
# nginx must be listening on all active IPs on port 8080
# You cannot use apt-get remove
awk '{sub(/#user www-data/,"user nginx")}1' /etc/nginx/nginx.conf > tmp && mv tmp /etc/nginx/nginx.conf
awk '{gsub(/80/,"8080")}1' /etc/nginx/sites-available/default > tmp && mv tmp /etc/nginx/sites-available/default
pkill apache2
chmod 644 /etc/nginx/nginx.conf
sudo service nginx restart
